Add meta data and like component to BlogItem
thrasherDGK/YABP pull request #2
Opened 2016-12-29 08:57 UTC by thrasherDGK

Also add some `propTypes` and `defaultProps` when necessary.

2017-01-06 09:15 UTC, thrasherDGK commented on src/components/BlogItem.jsx
> +  handleItemUpdate: PT.func,
@index01d Эдуард, когда пытаюсь добавить проверку `isRequired` возникает ошибка, что свойство не было передано при создании элемента `BlogItem`. Выставил брэйкпойт первой строкой конструктора, свойтсво там. Как так?

2017-01-19 06:29 UTC, index01d requested changes

2017-01-19 06:29 UTC, index01d commented on src/components/BlogItem.jsx
> +  handleItemUpdate: PT.func,
Ошибка возникает не в BlogItem, а в BlogList,  где функции у элементов items нет, но тем не менее используется та же спецификация для items.

2017-01-22 15:00 UTC, igor-ladkin commented on src/components/BlogItem.jsx
> +  handleItemUpdate: PT.func,
@index01d ага, понял, а как тогда по уму сделать? Просто отфильтровать ненужное свойство пойдет? Или есть лучше вариант?
p.s. последний коммит глянь, там просто отфильтровал ненужное. Вроде теперь норм.

2017-01-22 15:33 UTC, merged