Setup webpack
thrasherDGK/YABP pull request #4
Opened 2017-02-08 07:12 UTC by thrasherDGK

As for now just setup build system and integrate semantic UI. Updating existing layout/components will go in the following PR.

2017-02-09 09:13 UTC, index01d requested changes
Линтер при запуске `./node_modules/eslint/bin/eslint.js --ext .jsx,.js src/.`
возвращает ряд проблем, которые нужно поправить.

2017-02-09 09:13 UTC, index01d commented on src/components/BlogList.jsx
> +import _ from 'lodash';
Нужно импортировать конкретные функции
e.g.:
`import { pick } from 'lodash/object';`

2017-02-09 09:13 UTC, index01d commented on src/containers/BlogPage.jsx
> +import BlogList from '../components/BlogList';
Лучше избегать относительных путей. Использовать просто `from 'components/BlogList'` и.т.д

2017-02-09 09:16 UTC, thrasherDGK commented on src/components/BlogList.jsx
> +import _ from 'lodash';
ок

2017-02-09 09:16 UTC, thrasherDGK commented on src/containers/BlogPage.jsx
> +import BlogList from '../components/BlogList';
поправим

2017-02-13 10:24 UTC, thrasherDGK commented on src/components/BlogList.jsx
> +import _ from 'lodash';
@index01d сделал как ты посоветовал, но что-то раньше вроде код более понятный был. Особенно если посмотреть на `BlogPage` компонент.
```js
_.chain(items)
 .filter(({ meta }) => Number(meta.likeCount) > 0)
 .map(({ text, meta }) => [text, Number(meta.likeCount)])
 .value();
```
как-то вроде более понятно, что `map, filter, value` - это тоже функии лодаша. Какие преимущества в явном импорте нужных функиций по сравнению с импортом всего объекта `_`?

2017-02-13 11:00 UTC, index01d commented on src/components/BlogList.jsx
> +import _ from 'lodash';
потенциальная возможность собрать в итоговый бандл только используемые модули lodash, вместо того, чтобы тащить всех, меньший объем памяти занимаемый используемым объектом.

2017-02-21 14:33 UTC, thrasherDGK commented
@index01d я вроде твои замечания поправил, но апрува так и не дождался. Смерджу, если что не так, то отпиши потом.

2017-02-21 14:33 UTC, merged