Declarative middleware for API requests
thrasherDGK/YABP pull request #8
Opened 2017-03-03 10:22 UTC by thrasherDGK

2017-03-04 00:44 UTC, thrasherDGK commented
@index01d не уверен, что стоило `search.value` тоже в сторе хранить... Может обычный конролируемый инпут был бы лучше, но я пока не буду менять до твоего фидбэка.

2017-03-05 12:21 UTC, index01d commented
вполне можно хранить.

2017-03-05 12:23 UTC, index01d requested changes
В целом неплохо. Однако, есть нехорошая практика в месте, где используешь path-хелпер для формирования адреса ресурса REST API, они ведь совсем не обязаны быть одинаковыми и по сути это та еще мина на будущее. Ну и вообще path-хелпер предназначен для генерации ссылки внутри приложения, если хочется генерализации, то лучше создать еще один тип хелпера для генерации адреса ресурса в API.
И еще: почему About остался прежним (с запросом аж в view)?:)

2017-03-05 13:02 UTC, thrasherDGK commented
> они ведь совсем не обязаны быть одинаковыми и по сути это та еще мина на будущее

эт, да... тут я что-то не подумал...

> почему About остался прежним (с запросом аж в view)
 ну вот как-то так 🤣 🤣 🤣 поправим

2017-03-06 06:40 UTC, thrasherDGK commented
@index01d поправил замечания

2017-03-06 08:49 UTC, index01d approved these changes

2017-03-06 10:09 UTC, merged